#!/usr/bin/env python

# This is a quick and dirty example of how to use the MoteIF interface in
# Python


import os
import httplib
from tinyos.message import MoteIF
from threading import Thread

goali_server = "web.sld.cs.columbia.edu"
request = "/demo_sense_environment/default/call/run/insert_counter?"

class SerialForwarder(Thread):
	def __init__ (self):
		Thread.__init__(self)
	def run(self):
		os.system("./sf/sf 9002 /dev/ttyUSB0 115200")
      

class MyClass:
	def __init__(self):
		# Create a MoteIF
		self.mif = MoteIF.MoteIF()
		# Attach a source to it
		self.source = self.mif.addSource("sf@localhost:9002")

		 # SomeMessageClass.py would be generated by MIG
		self.mif.addListener(self, EnvSerialMsg)
		self.conn = httplib.HTTPConnection(goali_server)

	# Called by the MoteIF's receive thread when a new message
	# is received
	def receive(self, src, msg):
		print "Received message: "+ str(msg)
		self.conn = httplib.HTTPConnection(goali_server)
		complete_request = "%snode=%s&counter=%s&temp=%s&hum=%s&light=%s"%(request, 
				msg.get_node_id(), msg.get_counter(), msg.get_temp(),
                                                        msg.get_hum(), msg.get_light())
		print complete_request
		self.conn.request("GET", complete_request)
		r1 = self.conn.getresponse()

	def testURL(self):
		conn = httplib.HTTPConnection(goali_server)
		conn.request("GET", "%snode=%s&value=%s"%(request, "3", "5"))
		r1 = conn.getresponse()


if __name__ == "__main__":
	if not os.path.exists("./sf/sf"): 
		print "Missing Serial Forwarder"
		print "Goto ./sf and do"
		print "./bootstrap"
		print "./configure"
		print "make"
		exit()


	try:
		print "Clean *SerialMsg Files"
		os.remove("*SerialMsg.py*")
	except:
		pass

	try:
		print "MIG SerialMsg Files"
		os.system("mig python -target=null -python-classname=EnvSerialMsg ../SenseEnvironmentApp.h env_msg -o EnvSerialMsg.py")

		from EnvSerialMsg import *
	except:
		print "Failed to generate python class"
		exit()

	try:
		print "Starting Serial Forwarder"
		#t = SerialForwarder()
		#t.start()
	except:
		print "Failed to start Serial Forwarder"
		exit()


	m = MyClass()

	m.testURL()

